[theme]
primary_color = "#0093D0"
secondary_color = "#00A78F"
background_gradient = true
font_family = "Raleway"

[hero]
title = "Digitize your physical music collection"
description = "Gnedby is a simple tool to help you digitize your physical music collection."
image_url = "/portfolio/gnedby/assets/hero_image.png"

[hero.main_button]
text = "Star on Github"
url = "https://github.com/kennycha/gnedby"

[hero.sub_button]
text = "View on Crates.io"
url = "https://crates.io/crates/gnedby"

[features]
title = "Complete music collection management"
subtitle = "CLI & web interfaces, multiple formats, duplicate prevention"

[[features.items]]
title = "Apple Music Integration"

[[features.items]]
title = "Multi-Format Support"

[[features.items]]
title = "Duplicate Prevention"

[[features.items]]
title = "Web & CLI Interface"


[how_it_works]
title = "How Gnedby Works"
description = "Transform your physical music collection into a digital catalog. Track albums, prevent duplicates, and organize across all formats with ease."

[[how_it_works.steps]]
title = "Install CLI Tool"
description = "Install gnedby via Cargo with 'cargo install gnedby --locked'"

[[how_it_works.steps]]
title = "Add Your Albums"
description = "Add albums automatically via Apple Music ID or manually enter details"

[[how_it_works.steps]]
title = "Manage Collection"
description = "View, filter, and organize your collection across CD, LP, USB, and tape formats"

[[how_it_works.steps]]
title = "Sync & Browse"
description = "Synchronize with remote storage and browse via web interface"
