[theme]
primary_color = "#96B7C5"
secondary_color = "#83AEA2"
background_gradient = true
font_family = "Crimson Text"

[hero]
title = "Monitor agents from your menubar"
description = "AI agent monitoring tool in your macOS menubar"
image_url = "/portfolio/checka/assets/hero_image.png"

[hero.main_button]
text = "Star on Github"
url = "https://github.com/kennycha/checka"

[features]
title = "Essential features for AI-powered development"
subtitle = "Real-time monitoring, seamless workflow, never miss a beat"

[[features.items]]
title = "Real-time Agent Monitoring"

[[features.items]]
title = "Color-coded Status Indicators"

[[features.items]]
title = "Menubar Integration"

[how_it_works]
title = "How Checka Works"
description = "Monitor your AI agents in real-time without missing completed tasks. Simple installation, instant visibility, and seamless workflow integration."

[[how_it_works.steps]]
title = "Install"
description = "Build locally or run in development mode on your macOS system"

[[how_it_works.steps]]
title = "Launch"
description = "Run 'checka' command in your project directory to start monitoring"

[[how_it_works.steps]]
title = "Monitor"
description = "See real-time AI agent status in your menubar with color-coded indicators"

[[how_it_works.steps]]
title = "Stay Focused"
description = "Work on other tasks while agents process, never miss completion again"
