[theme]
primary_color = "#FF6C2B"
secondary_color = "#FFDE00"
background_gradient = true
font_family = "Lato"

[hero]
title = "Drop ideas, watch them grow"
description = "AI-powered idea development tool"
image_url = "/portfolio/seednote/assets/hero_image.png"

[hero.main_button]
text = "Star on Github"
url = "https://github.com/kennycha/seednote"

[hero.sub_button]
text = "View Project Live"
url = "https://kennycha.github.io/seednote/"

[features]
title = "Powerful features for idea development"
subtitle = "Local AI processing, privacy-first design, instant results"

[[features.items]]
title = "Local LLM Integration"

[[features.items]]
title = "MoSCoW Analysis"

[[features.items]]
title = "3 Stack Recommendations"

[how_it_works]
title = "How Seednote Works"
description = "Transform raw ideas into actionable projects with AI-powered technology recommendations."

[[how_it_works.steps]]
title = "Drop Your Idea"
description = "Input any project idea or concept you want to explore and develop"

[[how_it_works.steps]]
title = "Local AI Processing"
description = "Your local LLM analyzes the idea while keeping everything private on your machine"

[[how_it_works.steps]]
title = "Get Stack Recommendations"
description = "Receive MoSCoW analysis and 3 different technology stack combinations tailored to your project"

[[how_it_works.steps]]
title = "Watch Ideas Grow"
description = "Store, manage, and iterate on your ideas with structured development paths"
