[theme]
primary_color = "#949078"
secondary_color = "#C59E7E"
background_gradient = true
font_family = "JetBrains Mono"

[hero]
title = "Keep your cursor chats"
description = "Cursor extension that saves your chat history as a markdown file"
image_url = "/portfolio/cursor-chat-keeper/assets/hero_image.png"

[hero.main_button]
text = "Star on Github"
url = "https://github.com/kennycha/cursor-chat-keeper"

[hero.sub_button]
text = "View on Marketplace"
url = "https://marketplace.visualstudio.com/items?itemName=kennycha.cursor-chat-keeper"

[features]
title = "Essential features for conversation preservation"
subtitle = "Automatic export, organized formatting, persistent storage"

[[features.items]]
title = "Automatic Chat Export"

[[features.items]]
title = "Markdown Formatting"

[[features.items]]
title = "Context Preservation"

[[features.items]]
title = "Cross-Platform Support"

[how_it_works]
title = "How Cursor Chat Keeper Works"
description = "Preserve your valuable AI conversations in Cursor with markdown export. Never lose context or insights from your coding sessions again."

[[how_it_works.steps]]
title = "Install Extension"
description = "Install from Marketplace and activate in Cursor"

[[how_it_works.steps]]
title = "Chat Normally"
description = "Have conversations with AI in Cursor as usual"

[[how_it_works.steps]]
title = "Save with Shortcut"
description = "Use Ctrl+Alt+C or Command Palette to write chat history to a markdown file"

[[how_it_works.steps]]
title = "Get Markdown File"
description = "Receive organized cursor-chat.md with timestamped conversations and context"

