[theme]
primary_color = "#FF5157"
secondary_color = "#C355B4"
background_gradient = true
font_family = "Inter"

[hero]
title = 'Convert links into a single video'
description = "Convert Youtube links into a single video, with a custom background image"
image_url = "/portfolio/links2video/assets/hero_image.png"

[hero.main_button]
text = "Star on Github"
url = "https://github.com/kennycha/links2video"

[hero.sub_button]
text = "View Results"
url = "https://www.youtube.com/@kennycha-d5t"

[features]
title = "Essential features for video creation"
subtitle = "Automated processing, custom backgrounds, batch support"

[[features.items]]
title = "YouTube Audio Extraction"

[[features.items]]
title = "Audio Merging & Sync"

[[features.items]]
title = "Custom Background Design"

[how_it_works]
title = "How Links2Video Works"
description = "Transform multiple YouTube links into a cohesive video experience. Automated audio extraction, merging, and custom background generation in minutes."

[[how_it_works.steps]]
title = "Prepare Your Links"
description = "Create a text file with YouTube URLs, one per line, in the inputs directory"

[[how_it_works.steps]]
title = "Customize Background"
description = "Edit color palette and character overlay to match your creative vision"

[[how_it_works.steps]]
title = "Run CLI Command"
description = "Execute 'l2v filename.txt' and let automation handle the rest"

[[how_it_works.steps]]
title = "Get Your Video"
description = "Receive a single merged video with custom background and combined audio"

